### ISSUE TITLE
problem with memset_s

### ISSUE THREAD

**Issue by emivilla** [nhartland/APFELgrid#4]
I am working with Ubuntu 18.04 and g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0 version.
When I run make check, I get the following error: 

> In file included from tests/example_conv.cc:15:0:
./src/APFELgrid/fastkernel.h: In instantiation of ‘void NNPDF::FKTable<T>::Convolute(NNPDF::FKTable<T>::extern_pdf, const size_t&, T*) [with T = float; NNPDF::FKTable<T>::extern_pdf = void (*)(const double&, const double&, const long unsigned int&, float*); size_t = long unsigned int]’:
tests/example_conv.cc:57:32:   required from here
./src/APFELgrid/fastkernel.h:956:13: error: ‘memset_s’ was not declared in this scope
     memset_s(pdf,0,Psz);

**Comment by vbertone** [comment]
Dear @emivilla,

could you please try to replace the two occurrences of:

    memset_s(pdf,0,Psz);

in src/APFELgrid/fastkernel.h.in with:

    std::memset(pdf,0,Psz);

and rerun the installation script?

Valerio

**Comment by scarrazza** [comment]
Changing `memset_s` to `memset` will fix this issue.  `memset_s` is a feature of the C11 iso which, as far as I can tell, is not enabled by default in `gcc` (and btw requires the definition of the `__STDC_WANT_LIB_EXT1__` macro).

However I am not sure why `memset_s` was introduced in 4e7238adc1c6d49c3aa6b119b499bdd2fc653c1a, maybe @nhartland can comment on that?
